version: "3"
services:
  go-docker:
    build:
      context: .
      dockerfile: ./Dockerfile-server
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    volumes:
      - ./:/server
      - ../avatars:/server/avatars

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "DB_Planexa"
      POSTGRES_USER: "Planexa"
      POSTGRES_PASSWORD: "WEB21Planexa"
    ports:
      - "5432:5432"
    volumes:
      - ./db_postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./sessions:/var/lib/redis
