FROM golang:latest

WORKDIR /session

COPY go.mod ./
COPY go.sum ./

RUN go mod download

RUN go install github.com/githubnemo/CompileDaemon@latest && go mod tidy

COPY . .

EXPOSE 8081

ENTRYPOINT CompileDaemon -build="go build ./user_microservice/server/" -command=./server
