FROM golang:latest

WORKDIR /session

COPY go.mod ./
COPY go.sum ./

RUN go mod download

RUN go install github.com/githubnemo/CompileDaemon@latest && go mod tidy

COPY . .

EXPOSE 8081

ENTRYPOINT CompileDaemon -build="go build -o session ./auth_microservice/server_session_ms/" -command=./session
