version: "3"
services:
  go-docker:
    build:
      context: .
      dockerfile: ./Dockerfile-server
    depends_on:
      - postgres
      - session
    ports:
      - "8080:8080"
    volumes:
      - ./:/server
      - ./avatars:/server/avatars
      - ./img_boards:/server/img_boards

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "DB_Planexa"
      POSTGRES_USER: "Planexa"
      POSTGRES_PASSWORD: "WEB21Planexa"
    ports:
      - "5432:5432"
    volumes:
      - ./db_postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./sessions:/var/lib/redis

  session:
    build:
      context: .
      dockerfile: ./Dockerfile-session
    container_name: "2022_1_samoekrnaz_session_1"
    depends_on:
      - redis
    ports:
      - "8081:8081"
    volumes:
      - ./:/session

  userms:
    build:
      context: .
      dockerfile: ./Dockerfile-userms
    container_name: "2022_1_samoekrnaz_userms_1"
    depends_on:
      - session
    ports:
      - "8083:8083"
    volumes:
      - ./:/userms
