FROM golang:latest

WORKDIR /server

COPY go.mod ./
COPY go.sum ./

RUN go mod download

RUN go get github.com/githubnemo/CompileDaemon && go mod tidy

COPY . .

EXPOSE 8080

ENTRYPOINT CompileDaemon --build="go build initial_router_config.go main.go" --command=./main