version: "3"
services:
  go-docker:
    build:
      context: .
      dockerfile: ./Dockerfile-server
    depends_on:
      - postgres
      - session
      - user_microservice
    ports:
      - "8080:8080"
    volumes:
      - ./:/server
      - ./avatars:/server/avatars
      - ./img_boards:/server/img_boards

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "DB_Planexa"
      POSTGRES_USER: "Planexa"
      POSTGRES_PASSWORD: "WEB21Planexa"
    ports:
      - "5432:5432"
    volumes:
      - ./db_postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./sessions:/var/lib/redis

  session:
    build:
      context: .
      dockerfile: ./Dockerfile-session
    container_name: "2022_1_samoekrnaz_session_1"
    depends_on:
      - redis
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - ./:/session

  user_microservice:
    build:
      context: .
      dockerfile: Dockerfile-user
    container_name: "2022_1_samoekrnaz_user_microservice_1"
    depends_on:
      - session
    ports:
      - "8083:8083"
      - "8084:8084"
    volumes:
      - ./:/user

  prometheus:
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    depends_on:
      - nodeexporter
    volumes:
      - ./metrics/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: "grafana/grafana-enterprise"
    depends_on:
      - prometheus
    volumes:
      - ./grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"

  nodeexporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
    ports:
      - "9100:9100"
