FROM golang:latest

WORKDIR /server

COPY go.mod ./
COPY go.sum ./

RUN apt-get update && apt-get -y install libwebp-dev

RUN go mod download

RUN go install github.com/githubnemo/CompileDaemon@latest && go mod tidy

COPY . .

EXPOSE 8080

ENTRYPOINT CompileDaemon -build="go build -o server ./cmd/api/" -command=./server
