FROM golang:latest

WORKDIR /user

COPY go.mod ./
COPY go.sum ./

RUN go mod download

RUN go install github.com/githubnemo/CompileDaemon@latest && go mod tidy

COPY . .

EXPOSE 8083

ENTRYPOINT CompileDaemon -build="go build -o user ./user_microservice/server_user_ms/" -command=./user
