FROM golang:latest

WORKDIR /server

COPY go.mod ./
COPY go.sum ./

RUN go mod download

RUN go install github.com/githubnemo/CompileDaemon@latest && go mod tidy

COPY . .

EXPOSE 8080

ENTRYPOINT CompileDaemon -build="go build ./cmd/api/" -command=./api
