name: CI

on:
  pull_request:
    branches: [ '**' ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Verify dependencies
      run: go mod verify

    - name: Download library
      run: sudo apt-get update; sudo apt-get install libwebp-dev;

    - name: Run go vet
      run: go vet ./...

    - name: Install golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.45.2

    - name: Run golangci-lint
      run: golangci-lint run

    - name: Run tests
      run: go test -race -coverpkg=./... -coverprofile=c.out ./...; go tool cover -func=c.out
