name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:

    runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                go-version: 1.17

            - name: Verify dependencies
              run: go mod verify

            - name: Download library
              run: sudo apt-get update; sudo apt-get install libwebp-dev;

            - name: Run go vet
              run: go vet ./...

            - name: Install staticcheck
              run: go install honnef.co/go/tools/cmd/staticcheck@latest

            - name: Run staticcheck
              run: staticcheck ./...

            - name: Install golint
              run: go install golang.org/x/lint/golint@latest

            - name: Run golint
              run: golint ./...

            - name: Run tests
              run: go test -race -vet=off ./...