// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonF434a83fDecodePLANEXABackendModels(in *jlexer.Lexer, out *CheckListItems) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(CheckListItems, 0, 1)
			} else {
				*out = CheckListItems{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 CheckListItem
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF434a83fEncodePLANEXABackendModels(out *jwriter.Writer, in CheckListItems) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v CheckListItems) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF434a83fEncodePLANEXABackendModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CheckListItems) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF434a83fEncodePLANEXABackendModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CheckListItems) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF434a83fDecodePLANEXABackendModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CheckListItems) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF434a83fDecodePLANEXABackendModels(l, v)
}
func easyjsonF434a83fDecodePLANEXABackendModels1(in *jlexer.Lexer, out *CheckListItem) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id_clit":
			out.IdClIt = uint(in.Uint())
		case "title":
			out.Description = string(in.String())
		case "id_cl":
			out.IdCl = uint(in.Uint())
		case "id_t":
			out.IdT = uint(in.Uint())
		case "isready":
			out.IsReady = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF434a83fEncodePLANEXABackendModels1(out *jwriter.Writer, in CheckListItem) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id_clit\":"
		out.RawString(prefix[1:])
		out.Uint(uint(in.IdClIt))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"id_cl\":"
		out.RawString(prefix)
		out.Uint(uint(in.IdCl))
	}
	{
		const prefix string = ",\"id_t\":"
		out.RawString(prefix)
		out.Uint(uint(in.IdT))
	}
	{
		const prefix string = ",\"isready\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsReady))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CheckListItem) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF434a83fEncodePLANEXABackendModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CheckListItem) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF434a83fEncodePLANEXABackendModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CheckListItem) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF434a83fDecodePLANEXABackendModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CheckListItem) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF434a83fDecodePLANEXABackendModels1(l, v)
}
