global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'system'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:9100']

  - job_name: 'session_ms'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'host.docker.internal:8082']
