global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'system'
    metrics_path: /metrics
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'session_ms'
    metrics_path: /metrics
    static_configs:
      - targets: ['session:8082']

  - job_name: 'user_ms'
    metrics_path: /metrics
    static_configs:
      - targets: ['user_microservice:8084']

  - job_name: 'api'
    metrics_path: /metrics
    static_configs:
      - targets: ['go-docker:8080']
